# Generated by Django 5.1.5 on 2025-01-29 03:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("outer", "아우터"),
                    ("top", "상의"),
                    ("bottom", "하의"),
                    ("shoes", "신발"),
                    ("bag", "가방"),
                    ("accessories", "악세사리"),
                ],
                max_length=50,
            ),
        ),
    ]
