# Generated by Django 5.1.5 on 2025-01-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="none", max_length=100),
        ),
    ]
