# Generated by Django 5.1.5 on 2025-01-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=100),
        ),
    ]
