# Generated by Django 5.1.5 on 2025-01-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("red", "레드"),
                            ("orange", "오렌지"),
                            ("yellow", "옐로우"),
                            ("green", "그린"),
                            ("blue", "블루"),
                            ("khaki", "카키"),
                            ("navy", "네이비"),
                            ("purple", "퍼플"),
                            ("black", "블랙"),
                            ("white", "화이트"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("spring", "봄"),
                            ("summer", "여름"),
                            ("fall", "가을"),
                            ("winter", "겨울"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="curation",
            name="color",
        ),
        migrations.RemoveField(
            model_name="curation",
            name="season",
        ),
        migrations.AddField(
            model_name="curation",
            name="color",
            field=models.ManyToManyField(related_name="curations", to="curation.color"),
        ),
        migrations.AddField(
            model_name="curation",
            name="season",
            field=models.ManyToManyField(
                related_name="curations", to="curation.season"
            ),
        ),
    ]
