# Generated by Django 5.1.5 on 2025-01-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0002_color_season_remove_curation_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="season",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
