# Generated by Django 5.1.5 on 2025-01-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curation", "0003_alter_color_name_alter_season_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="curation",
            old_name="color",
            new_name="colors",
        ),
        migrations.RenameField(
            model_name="curation",
            old_name="season",
            new_name="seasons",
        ),
    ]
