# Generated by Django 5.1.5 on 2025-01-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="social_account_type",
            field=models.CharField(
                choices=[
                    ("google", "Google"),
                    ("kakao", "Kakao"),
                    ("naver", "Naver"),
                    ("apple", "Apple"),
                ],
                default="kakao",
                max_length=20,
            ),
        ),
    ]
